### Model params
# AlexNet/ResNet/VGG
backbone: "ResNet50"
lr: 1e-4
epoch: 100
alpha: 0.05
weight_decay: 10 ** -5
momentum: 0.9
num_bits: 64
batch_size: 32
checkpoint: 10

### Dataset params
# coco/nuswide/flick/imagenet/cifar10/flickr
dataset: "nuswide"
resize_size: 256
crop_size: 224
num_workers: 4
topK: 5000
n_class: 10
data_path: "/data2/fyang/data"
txt_path: "./data/"

### attack settings
hash_model: "DPSH"
attack_method: "dhta"
n_t: 9
epsilon: 0.03
iteration: 1
transfer: True
trans_config:
  t_hash_model: "CSQ"
  t_bit: 64
  t_backbone: "VGG11"

### other configs
log_path: "./log/attack"
save_path: "./save/attack"
hash_save_path: "./save/hashing"
gpu: 0
seed: 2021