### Model params
# AlexNet/ResNet/VGG
backbone: "ResNet34"
lr: 1e-4
epoch: 200
alpha: 0.05
weight_decay: 10 ** -5
momentum: 0.9
num_bits: 64
batch_size: 256
checkpoint: 10

### Dataset params
# coco/nuswide/flick/imagenet/cifar10/flickr
dataset: "nuswide"
resize_size: 256
crop_size: 224
num_workers: 4
topK: 5000
n_class: 10
data_path: "/data2/fyang/data"
txt_path: "./data/"

### Deep Hash settings
hash_model: "CSQ"
train: True
test: True
hashnet_params:
  alpha: 0.1
  step_continuation: 20
csq_params:
  lambda_: 0.0001

### other configs
log_path: "./log/hashing"
save_path: "./save/hashing"
gpu: 0
seed: 2021
